Fix error in date_start and date_end for piControl
Ouranosinc/xscen pull request #84
Opened 2022-09-23 19:08 UTC by juliettelavoie

### Pull Request Checklist:
- [ ] `pre-commit` hooks are installed/active in my local clone (`$ pre-commit install`)
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #83 
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [ ] If a merge request has been made in parallel to this PR in xscen-notebooks, it is merged and the submodules have been updated.
- [ ] HISTORY.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* If the list of selected files is empty, the new coverage test (guessed_nb_hrs _sum) creates an error. guessed_nb_hrs =0 hours breaks the division and throws a `OverflowError: Python int too large to convert to C long`. When nothing has been selected, I make sure the test is passed, just to avoid the 0.
* When the sum is really big, pandas has difficulty converting it to do the division and also throws OverflowError: Python int too large to convert to C long`. Doing the divisions with the nano integers works.
* Cast dates to %4Y for reasons explained in issue 83.

### Does this PR introduce a breaking change?

yes, the catalogs will now have the right dates.
### Other information:

2022-09-23 19:17 UTC, juliettelavoie commented
attendez avant de aire la revue, il y a un problème.

2022-09-23 19:31 UTC, aulemahal commented
Je pense qu'on a besoin que "date_start" et "date_end" soient des `Period`. Si possible, il faudrait faire le strftime juste au moment d'écrire sur disque!

2022-09-26 13:48 UTC, juliettelavoie commented
> Je pense qu'on a besoin que "date_start" et "date_end" soient des `Period`. Si possible, il faudrait faire le strftime juste au moment d'écrire sur disque!

J'ai essayé de le descendre plus bas (sous drop_duplicates), mais dans ce cas on doit modifier les dates de tout le catalogue, au lieu de juste les nouvelles lignes. De ce que je comprends, `check_valid` et `drop_duplicates` n'utilise pas les Periods. Je suis pas sur de comprendre pourquoi ce n'était pas correct à l'endroit où je l'avais mis au début (sous `df = pd.DataFrame(df).transpose()`)

2022-09-26 13:57 UTC, aulemahal commented
Ma proposition c'est justement de ne modifier que le catalogue qu'on écrit sur disque, ça implique qu'au moment de faire la conversion, on doit _tout_ convertir en string, avant d'écrire la version convertie. C'est l'écriture qui bogue, pas la lecture.

Là le catalogue en mémoire contient des String plutôt que des Period. Il me semble qu'on ne veut pas ça? Parce que le bogue c'est justement que les objets Period se sérialisent mal, si on ne jouait qu'avec des String, on n'aurait pas le problème.

2022-09-26 17:07 UTC, juliettelavoie commented
Ok je pense que ça marche maintenant.

2022-09-26 17:50 UTC, aulemahal requested changes
Tu convertis les Period en Str, mais ensuite tu mets ces Str dans le catalogue en mémoire, je pense qu'on ne veut pas ça. 

Je ne peux pas proposer des changements pour des sections non modifiées, mais ceci est ma proposition pour ce qui suit mon autre proposition:

```python
        if self.meta_file is not None:
            with fs.open(self.esmcat.catalog_file, "wb") as csv_outfile:
                df_str.to_csv(csv_outfile, index=False, compression=None)
        else:
            read_csv_kwargs = deepcopy(self.read_csv_kwargs)
            del read_csv_kwargs['parse_dates']
            del read_csv_kwargs['date_parser']
            # Update the catalog file saved on disk
            disk_cat = DataCatalog(
                {
                    "esmcat": self.esmcat.dict(),
                    "df": pd.read_csv(self.esmcat.catalog_file, **read_csv_kwargs),
                }
            )
            disk_cat.esmcat._df = pd.concat([disk_cat.df, df_str])
            disk_cat.check_valid()
            disk_cat.drop_duplicates()
            with fs.open(disk_cat.esmcat.catalog_file, "wb") as csv_outfile:
disk_cat.df.to_csv(csv_outfile, index=False, compression=None)
```
Où dans le `else` on lit les données sans parser les Periods pour éviter d'avoir à convertir ce qui est déjà sur disque.

2022-09-26 17:50 UTC, aulemahal commented on HISTORY.rst
> +* Cast caltalog date_start and date_end to "%4Y-%m-%d %H:00". (:issue:`83`, :pull:`79`)
```suggestion
* Cast catalog date_start and date_end to "%4Y-%m-%d %H:00" when writing to disk. (:issue:`83`, :pull:`79`)
```

2022-09-26 17:50 UTC, aulemahal commented on xscen/catalog.py
> +            self.esmcat._df = df_fix_date
```suggestion
            df_str = df_fix_date
        else:
            df_str = self.df
```

2022-09-26 18:03 UTC, RondeauG commented on xscen/extract.py
> +        # if no files are selected we don't want the warming and guessed_nb_hrs_sum=0 breaks the code
```suggestion
        # if no files are selected we don't want the warning and guessed_nb_hrs_sum=0 breaks the code
```

2022-09-26 18:13 UTC, RondeauG commented
I don't reallt have any other changes. I'd accept the PR, but I want to let Pascal check if the changes dones reflect his comment first.

2022-09-26 18:35 UTC, juliettelavoie commented on xscen/extract.py
> +        # if no files are selected we don't want the warning and guessed_nb_hrs_sum=0 breaks the code
t'as raison, le commentaire ne fait pas de sens. Je voulais juste dire que je veux pas faire la division quand guessed_nb_hrs_sum=0. Je vais changere

2022-09-26 19:48 UTC, merged